version: '3.2'
services:
  samba:
    image:  thepacho/samba4ad
    privileged: true
    hostname: ad.example.local
    container_name: samba4
    environment:
      SAMBA_DC_REALM: example.local
      SAMBA_DC_DOMAIN: example
      SAMBA_DC_ADMIN_PASSWD: Example2023*!
      SAMBA_DC_DNS_BACKEND: SAMBA_INTERNAL
      TZ: America/Bogota

    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 139:139
      - 389:389
      - 389:389/udp
      - 445:445
      - 464:464
      - 464:464/udp
      - 636:636
      - 3268-3269:3268-3269
    volumes:
      - ./data:/var/lib/samba
      - ./config:/etc/samba
